[package]
name = "gfastaml"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0" # easy idiomatic error handling
clap = "4.5"   # command-line parser
fxread = "0.2.14" # barebones fastx reader

[dev-dependencies]
tempfile = "3" # temporary file library

